In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./all_data/test_c1000_d1000.csv")

In [3]:
df

,0,1,1.1,1.2,0.1,0.2,1.3,1.4,0.3,1.5,...,1.253,0.238,1.254,0.239,1.255,1.256,1.257,0.240,1.258,1.259
0,1,0,1,1,0,0,0,0,0,1,...,1,0,1,1,0,1,0,1,1,0
1,1,0,1,0,0,0,1,1,0,1,...,1,0,1,0,1,1,1,0,0,1
2,0,0,0,1,1,1,0,0,1,1,...,1,0,0,0,0,1,0,0,0,0
3,0,1,0,1,0,1,1,1,0,1,...,0,0,1,0,0,0,0,0,1,1
4,0,0,1,0,1,0,1,1,1,1,...,0,1,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,1,1,0,1,1,1,0,1,0,1,...,1,0,0,1,1,0,0,1,1,0
1995,1,0,0,1,0,1,0,1,0,1,...,0,0,0,0,1,0,1,0,1,1
1996,1,1,0,0,0,0,1,0,1,0,...,1,0,1,1,1,1,1,0,1,0
1997,0,1,1,0,1,0,1,1,0,0,...,1,0,0,0,0,1,1,1,0,1
1998,0,1,1,0,0,0,0,1,0,0,...,0,1,0,1,0,0,1,1,1,0

In [14]:
class node:
    

def var_impurity(K, K_0, K_1):
    return (K_0 * K_1) / K**2

def inf_gain(H, X, S):
    sum = 0
    #For each value in attribute X
    for x in X:
        K = len(x)
        K_0 = len(list(filter(lambda x: x == 0, x)))
        K_1 = len(list(filter(lambda x: x == 1, x)))
        sum = sum + len(X.get(x))/len(X) * var_impurity(K, K_0, K_1)
        
    return H - sum

def GrowTree(S):

[1]