In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("./all_data/test_c1000_d1000.csv")

In [7]:
my_dict = df

In [8]:
df

,0,1,1.1,1.2,0.1,0.2,1.3,1.4,0.3,1.5,...,1.253,0.238,1.254,0.239,1.255,1.256,1.257,0.240,1.258,1.259
0,1,0,1,1,0,0,0,0,0,1,...,1,0,1,1,0,1,0,1,1,0
1,1,0,1,0,0,0,1,1,0,1,...,1,0,1,0,1,1,1,0,0,1
2,0,0,0,1,1,1,0,0,1,1,...,1,0,0,0,0,1,0,0,0,0
3,0,1,0,1,0,1,1,1,0,1,...,0,0,1,0,0,0,0,0,1,1
4,0,0,1,0,1,0,1,1,1,1,...,0,1,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,1,1,0,1,1,1,0,1,0,1,...,1,0,0,1,1,0,0,1,1,0
1995,1,0,0,1,0,1,0,1,0,1,...,0,0,0,0,1,0,1,0,1,1
1996,1,1,0,0,0,0,1,0,1,0,...,1,0,1,1,1,1,1,0,1,0
1997,0,1,1,0,1,0,1,1,0,0,...,1,0,0,0,0,1,1,1,0,1
1998,0,1,1,0,0,0,0,1,0,0,...,0,1,0,1,0,0,1,1,1,0

In [82]:
class node:
    val = -1
    A = ""
    lNode = None
    rNode = None
    def __init(A, lNode, rNode):
        self.A = A
        self.lNode = lNode
        self.rNode = rNode
    
    def __init__(val):
        self.val = val
    
    def getVal():
        return val
    
def var_impurity(K, K_0, K_1):
    return (K_0 * K_1) / K**2

def inf_gain(H, X_col, S, tA):
    sum = 0
    K = len(S)
    for x in np.unique(S[X_col]):
        S_n = S[S[X_col] == x]
        K_v = len(S_n)
        K_0 = len(S_n[S_n[X_col] != x])
        K_1 = len(S_n[S_n[X_col] == x])
        sum = sum + (K_v / K) * var_impurity(K_v, K_0, K_1)
    return H - sum;

#Take in data S and target attribute tA
def GrowTree(S, tA):
    #Calculate entropy / variance impurity
    H = var_impurity(len(S), len(S[S[tA] == 0]), len(S[S[tA] == 1]))
    if ( all(x == 0 for x in list(S[tA])) ):
        return S
    elif ( all(x == 1 for x in list(S[tA])) ):
        return S
    else:
        max_gain = (0, 0)
        for col in S.drop(columns=[tA]):
            new_gain = inf_gain(H, col, S, tA)
            max_gain = (new_gain > max_gain[1]) if (col, new_gain) else max_gain
        x_j = max_gain[0]
        return x_j
        S_0 = S[S[x_j] == 0].reset_index()
        S_1 = S[S[x_j] == 1].reset_index()
        return node(x_j, GrowTree(S_0, tA), GrowTree(S_1, tA))

In [83]:
GrowTree(df, '1')

TypeError: 'bool' object is not subscriptable

In [63]:
max(col) for col in df.columns

SyntaxError: invalid syntax (<ipython-input-63-210975b21cec>, line 1)

In [37]:
df[df['1'] == 0].reset_index()

,index,0,1,1.1,1.2,0.1,0.2,1.3,1.4,0.3,...,1.253,0.238,1.254,0.239,1.255,1.256,1.257,0.240,1.258,1.259
0,0,1,0,1,1,0,0,0,0,0,...,1,0,1,1,0,1,0,1,1,0
1,1,1,0,1,0,0,0,1,1,0,...,1,0,1,0,1,1,1,0,0,1
2,2,0,0,0,1,1,1,0,0,1,...,1,0,0,0,0,1,0,0,0,0
3,4,0,0,1,0,1,0,1,1,1,...,0,1,1,0,0,0,1,0,0,0
4,6,0,0,1,0,1,1,1,1,1,...,0,1,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
936,1985,1,0,0,0,0,0,0,0,0,...,0,1,0,1,0,1,1,0,0,1
937,1986,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,1,0,1,0
938,1988,0,0,1,0,1,1,1,1,0,...,1,0,1,0,1,0,1,1,0,0
939,1993,1,0,0,1,1,0,1,0,0,...,1,1,1,0,0,1,1,1,0,1
940,1995,1,0,0,1,0,1,0,1,0,...,0,0,0,0,1,0,1,0,1,1